workflows:
  web-to-mobile-apk:
    name: Smart Budget Tracker - Web to Mobile APK (Final Working)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.11.0
      npm: 10.2.4
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - ~/.gradle/caches
    scripts:
      - name: Install dependencies and Capacitor
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
          
      - name: Build web app
        script: |
          # Build the web app
          npm run build || {
            echo "Build script failed, trying alternative..."
            npx vite build --outDir dist/public
          }
          
          # Ensure dist/public exists with content
          if [ ! -d "dist/public" ]; then
            echo "Creating dist/public structure..."
            mkdir -p dist/public
            if [ -d "dist" ]; then
              find dist -type f -name "*.html" -o -name "*.js" -o -name "*.css" | head -1 | xargs -I {} cp {} dist/public/ 2>/dev/null || true
            fi
          fi
          
          echo "Final build output:"
          ls -la dist/public/ || echo "dist/public not found"
          
      - name: Setup Capacitor without init conflict
        script: |
          # Create package.json entry for Capacitor (avoids init command)
          node -e "
            const pkg = require('./package.json');
            pkg.capacitor = {
              appId: 'com.smartbudgettracker',
              appName: 'Smart Budget Tracker',
              webDir: 'dist/public'
            };
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "
          
          # Create capacitor.config.json (JSON format to avoid TS conflict)
          cat > capacitor.config.json << 'EOF'
          {
            "appId": "com.smartbudgettracker",
            "appName": "Smart Budget Tracker",
            "webDir": "dist/public",
            "server": {
              "androidScheme": "https"
            }
          }
          EOF
          
          # Remove any existing capacitor.config.ts to avoid conflicts
          rm -f capacitor.config.ts
          
      - name: Add Android platform and copy assets
        script: |
          # Add Android platform directly (skip init)
          npx cap add android
          
          # Copy web assets
          npx cap copy android
          npx cap sync android
          
          # Verify assets
          echo "Android assets:"
          find android/app/src/main/assets -type f | head -10 || echo "No assets found"
          
      - name: Build signed APK
        script: |
          cd android
          
          # Create keystore
          keytool -genkey -v -keystore release.keystore \
            -alias release -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Smart Budget Tracker, OU=Mobile, O=App, L=City, S=State, C=NP" \
            -storepass release123 -keypass release123
          
          # Configure signing in build.gradle
          cat >> app/build.gradle << 'GRADLE'
          
          android {
              signingConfigs {
                  release {
                      storeFile file('../release.keystore')
                      storePassword 'release123'
                      keyAlias 'release'
                      keyPassword 'release123'
                  }
              }
              buildTypes {
                  release {
                      signingConfig signingConfigs.release
                      minifyEnabled false
                  }
              }
          }
          GRADLE
          
          # Build APK
          ./gradlew clean assembleRelease
          
          # Show results
          echo "Build complete! Generated files:"
          find app/build/outputs -name "*.apk" -o -name "*.aab"
          
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - developer@smartbudgettracker.com
