workflows:
  android-build:
    name: Smart Budget Tracker APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      npm: 9.6.7
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Create basic React Native app
        script: |
          npx @react-native-community/cli@latest init BudgetApp
          cd BudgetApp
          
      - name: Setup Android build
        script: |
          cd BudgetApp/android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "org.gradle.jvmargs=-Xmx4096M" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          
      - name: Build Android APK
        script: |
          cd BudgetApp/android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon
          
      - name: Prepare APK
        script: |
          cd BudgetApp
          APK_PATH=$(find android/app/build/outputs/apk/release -name "*.apk" | head -1)
          if [ -f "$APK_PATH" ]; then
            cp "$APK_PATH" ../SmartBudgetTracker.apk
            echo "✅ APK created successfully!"
            ls -la ../SmartBudgetTracker.apk
          else
            echo "❌ APK not found!"
            find android/app/build -name "*.apk" -type f
          fi
          
    artifacts:
      - SmartBudgetTracker.apk
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true
