workflows:
  expo-build:
    name: Smart Budget Tracker Expo Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: 18.17.0
      npm: 9.6.7
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          cd react-native-app
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
      - name: Build Android APK with Expo
        script: |
          cd react-native-app
          npx expo install --fix
          npx expo prebuild --platform android
          npx eas build --platform android --local --profile preview
    artifacts:
      - react-native-app/build-*.apk
      - react-native-app/build-*.aab
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true
