workflows:
  android-build:
    name: Smart Budget Tracker - Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.11.0
      npm: 10.2.4
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - ~/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Create basic React Native project
        script: |
          npx @react-native-community/cli@latest init SmartBudgetTracker
          cd SmartBudgetTracker
          
      - name: Create Smart Budget Tracker app
        script: |
          cd SmartBudgetTracker
          cat > App.tsx << 'EOF'
          import React from 'react';
          import { View, Text, StyleSheet, ScrollView, StatusBar } from 'react-native';

          const App = () => {
            return (
              <>
                <StatusBar barStyle="light-content" backgroundColor="#FF6B35" />
                <ScrollView style={styles.container}>
                  <View style={styles.header}>
                    <Text style={styles.title}>рд╕реНрдорд╛рд░реНрдЯ рдмрдЬреЗрдЯ рдЯреНрд░реНрдпрд╛рдХрд░</Text>
                    <Text style={styles.subtitle}>Smart Budget Tracker</Text>
                  </View>
                  
                  <View style={styles.content}>
                    <Text style={styles.sectionTitle}>рд╕реНрд╡рд╛рдЧрдд рдЫ!</Text>
                    <Text style={styles.description}>
                      рддрдкрд╛рдИрдВрдХреЛ рд╡реНрдпрдХреНрддрд┐рдЧрдд рдмрдЬреЗрдЯ рд░ рдЦрд░реНрдЪ рд╡реНрдпрд╡рд╕реНрдерд╛рдкрди рдЧрд░реНрди рдбрд┐рдЬрд╛рдЗрди рдЧрд░рд┐рдПрдХреЛ рдПрдк
                    </Text>
                    
                    <View style={styles.feature}>
                      <Text style={styles.featureTitle}>ЁЯПж рдмрдЬреЗрдЯ рд╡реНрдпрд╡рд╕реНрдерд╛рдкрди</Text>
                      <Text style={styles.featureDesc}>рдЖрдлреНрдирд╛ рдмрдЬреЗрдЯрд╣рд░реВ рд╕рд┐рд░реНрдЬрдирд╛ рд░ рдЯреНрд░реНрдпрд╛рдХ рдЧрд░реНрдиреБрд╣реЛрд╕реН</Text>
                    </View>
                    
                    <View style={styles.feature}>
                      <Text style={styles.featureTitle}>ЁЯТ╕ рдЦрд░реНрдЪ рдЯреНрд░реНрдпрд╛рдХрд┐рдВрдЧ</Text>
                      <Text style={styles.featureDesc}>рджреИрдирд┐рдХ рдЦрд░реНрдЪрд╣рд░реВ рд░реЗрдХрд░реНрдб рдЧрд░реНрдиреБрд╣реЛрд╕реН</Text>
                    </View>
                    
                    <View style={styles.feature}>
                      <Text style={styles.featureTitle}>ЁЯУК рдПрдирд╛рд▓рд┐рдЯрд┐рдХреНрд╕</Text>
                      <Text style={styles.featureDesc}>рддрдкрд╛рдИрдВрдХреЛ рдЦрд░реНрдЪ рдмрд┐рд╢реНрд▓реЗрд╖рдг рд╣реЗрд░реНрдиреБрд╣реЛрд╕реН</Text>
                    </View>
                    
                    <View style={styles.feature}>
                      <Text style={styles.featureTitle}>ЁЯУ╖ рд░рд╕рд┐рдж рдлреЛрдЯреЛ</Text>
                      <Text style={styles.featureDesc}>рд░рд╕рд┐рджрдХрд╛ рдлреЛрдЯреЛрд╣рд░реВ рд╕рдВрдЧреНрд░рд╣ рдЧрд░реНрдиреБрд╣реЛрд╕реН</Text>
                    </View>
                  </View>
                  
                  <View style={styles.footer}>
                    <Text style={styles.footerText}>KissonFloyd рджреНрд╡рд╛рд░рд╛ рдирд┐рд░реНрдорд┐рдд</Text>
                    <Text style={styles.version}>рд╕рдВрд╕реНрдХрд░рдг 1.0.0</Text>
                  </View>
                </ScrollView>
              </>
            );
          };

          const styles = StyleSheet.create({
            container: {
              flex: 1,
              backgroundColor: '#F8F9FA',
            },
            header: {
              backgroundColor: '#FF6B35',
              padding: 30,
              alignItems: 'center',
            },
            title: {
              fontSize: 28,
              fontWeight: 'bold',
              color: '#FFFFFF',
              marginBottom: 5,
            },
            subtitle: {
              fontSize: 16,
              color: '#FFE4D6',
            },
            content: {
              padding: 20,
            },
            sectionTitle: {
              fontSize: 24,
              fontWeight: 'bold',
              color: '#2C3E50',
              marginBottom: 15,
            },
            description: {
              fontSize: 16,
              color: '#5D6D7E',
              marginBottom: 25,
              lineHeight: 24,
            },
            feature: {
              backgroundColor: '#FFFFFF',
              padding: 20,
              marginBottom: 15,
              borderRadius: 12,
              elevation: 2,
              shadowColor: '#000',
              shadowOffset: { width: 0, height: 2 },
              shadowOpacity: 0.1,
              shadowRadius: 4,
            },
            featureTitle: {
              fontSize: 18,
              fontWeight: 'bold',
              color: '#2C3E50',
              marginBottom: 8,
            },
            featureDesc: {
              fontSize: 14,
              color: '#7F8C8D',
              lineHeight: 20,
            },
            footer: {
              padding: 20,
              alignItems: 'center',
              marginTop: 20,
            },
            footerText: {
              fontSize: 14,
              color: '#95A5A6',
              marginBottom: 5,
            },
            version: {
              fontSize: 12,
              color: '#BDC3C7',
            },
          });

          export default App;
          EOF
          
      - name: Build Android APK
        script: |
          cd SmartBudgetTracker/android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "org.gradle.jvmargs=-Xmx4096M" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon
          
      - name: Copy APK to artifacts
        script: |
          cd SmartBudgetTracker
          APK_FILE=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          if [ -f "$APK_FILE" ]; then
            cp "$APK_FILE" ../smart-budget-tracker.apk
            echo "тЬЕ Smart Budget Tracker APK ready!"
            ls -la ../smart-budget-tracker.apk
            echo "APK size: $(du -h ../smart-budget-tracker.apk | cut -f1)"
          else
            echo "тЭМ APK not found!"
            find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
          fi
          
    artifacts:
      - smart-budget-tracker.apk
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true
