workflows:
  android-build:
    name: Smart Budget Tracker - Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.11.0
      npm: 10.2.4
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - ~/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Create React Native project
        script: |
          npx @react-native-community/cli@latest init SmartBudgetTracker
          cd SmartBudgetTracker
          
      - name: Install Smart Budget Tracker dependencies
        script: |
          cd SmartBudgetTracker
          npm install @react-native-async-storage/async-storage@1.19.3
          npm install @react-navigation/native@6.1.9
          npm install @react-navigation/bottom-tabs@6.5.11
          npm install @react-navigation/stack@6.3.20
          npm install react-native-safe-area-context@4.6.3
          npm install react-native-screens@3.22.0
          npm install react-native-chart-kit@6.12.0
          npm install react-native-svg@13.9.0
          
      - name: Copy Smart Budget Tracker source code
        script: |
          # Copy app files from repository
          if [ -d "$CM_BUILD_DIR/react-native-app/src" ]; then
            cp -r $CM_BUILD_DIR/react-native-app/src SmartBudgetTracker/
            echo "✅ Copied Smart Budget Tracker source files"
          else
            echo "⚠️ No source files found, using template"
          fi
          
          # Copy App.tsx if it exists
          if [ -f "$CM_BUILD_DIR/react-native-app/App.tsx" ]; then
            cp $CM_BUILD_DIR/react-native-app/App.tsx SmartBudgetTracker/
            echo "✅ Copied Smart Budget Tracker App.tsx"
          else
            echo "⚠️ No App.tsx found, using template"
          fi
          
      - name: Build Android APK
        script: |
          cd SmartBudgetTracker/android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "org.gradle.jvmargs=-Xmx4096M" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleRelease --no-daemon
          
      - name: Copy APK to artifacts
        script: |
          cd SmartBudgetTracker
          APK_FILE=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          if [ -f "$APK_FILE" ]; then
            cp "$APK_FILE" ../smart-budget-tracker.apk
            echo "✅ Smart Budget Tracker APK ready!"
            ls -la ../smart-budget-tracker.apk
            echo "APK size: $(du -h ../smart-budget-tracker.apk | cut -f1)"
          else
            echo "❌ APK not found!"
            find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
          fi
          
    artifacts:
      - smart-budget-tracker.apk
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true
