workflows:
  basic-android-build:
    name: Smart Budget Tracker Simple Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      npm: 9.6.7
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Create React Native project
        script: |
          npx @react-native-community/cli@latest init SmartBudgetApp
          cd SmartBudgetApp
          
      - name: Configure for build
        script: |
          cd SmartBudgetApp/android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "org.gradle.jvmargs=-Xmx4096M" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          
      - name: Build APK
        script: |
          cd SmartBudgetApp
          npx react-native build-android --mode=release
          
      - name: Copy APK file
        script: |
          cd SmartBudgetApp
          find android -name "*.apk" -type f -exec cp {} ../smart-budget-tracker.apk \;
          ls -la ../smart-budget-tracker.apk || echo "APK not found"
          
    artifacts:
      - smart-budget-tracker.apk
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true
