workflows:
  android-build:
    name: Smart Budget Tracker - Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20.11.0
      npm: 10.2.4
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - ~/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          cd react-native-app
          npm cache clean --force
          npm install
          
      - name: Configure Expo build
        script: |
          cd react-native-app
          npx expo prebuild --platform android
          
      - name: Build Android APK
        script: |
          cd react-native-app/android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "org.gradle.jvmargs=-Xmx4096M" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon
          
      - name: Copy APK to artifacts
        script: |
          cd react-native-app
          APK_FILE=$(find android/app/build/outputs/apk/release -name "*.apk" -type f | head -1)
          if [ -f "$APK_FILE" ]; then
            cp "$APK_FILE" ../smart-budget-tracker.apk
            echo "✅ Smart Budget Tracker APK ready!"
            ls -la ../smart-budget-tracker.apk
            echo "APK size: $(du -h ../smart-budget-tracker.apk | cut -f1)"
          else
            echo "❌ APK not found!"
            find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
          fi
          
    artifacts:
      - smart-budget-tracker.apk
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true
