workflows:
  expo-build:
    name: Smart Budget Tracker Expo Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: 18.17.0
      npm: 8.19.4
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          cd react-native-app
          npm install --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g expo-cli@6.3.10
      - name: Expo login
        script: |
          cd react-native-app
          expo login --non-interactive
      - name: Build Android APK with Expo
        script: |
          cd react-native-app
          expo build:android --type apk --non-interactive
    artifacts:
      - react-native-app/*.apk
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true
