workflows:
  basic-android-build:
    name: Smart Budget Tracker Basic Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 16.20.0
      npm: 8.19.4
      ndk: r23c
      java: 11
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Create basic React Native project
        script: |
          npx react-native@latest init SmartBudgetTracker --version 0.72.6
          cd SmartBudgetTracker
          
          # Copy app.json configuration
          cat > app.json << 'EOF'
          {
            "name": "Smart Budget Tracker",
            "displayName": "Smart Budget Tracker",
            "version": "1.0.0"
          }
          EOF
          
      - name: Build Android APK
        script: |
          cd SmartBudgetTracker
          cd android
          ./gradlew assembleRelease
          
      - name: Copy APK to artifacts
        script: |
          cd SmartBudgetTracker
          cp android/app/build/outputs/apk/release/app-release.apk ../smart-budget-tracker.apk
          
    artifacts:
      - smart-budget-tracker.apk
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true
