workflows:
  expo-build:
    name: Smart Budget Tracker Expo Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: 18.17.0
      npm: latest
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          cd react-native-app
          npm ci
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
      - name: Expo login
        script: |
          cd react-native-app
          expo login --non-interactive
      - name: Build Android APK with Expo
        script: |
          cd react-native-app
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - react-native-app/*.apk
      - react-native-app/*.aab
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true

  react-native-android:
    name: Smart Budget Tracker Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.smartbudgettracker"
        GOOGLE_PLAY_TRACK: "internal"
      node: 18.17.0
      npm: latest
      ndk: r25c
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - ~/.gradle/caches
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          cd react-native-app
          npm ci
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/react-native-app/android/local.properties"
      - name: Build Android APK
        script: |
          cd react-native-app
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - react-native-app/android/app/build/outputs/**/*.apk
      - react-native-app/android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - kissonFloyd@example.com
        notify:
          success: true
          failure: true
