workflows:
  web-to-mobile-apk:
    name: Smart Budget Tracker - Web to Mobile APK (Exact Visual Match)
    # ... (previous configuration) ...
    scripts:
      - name: Build sophisticated web app
        script: |
          # Build the existing sophisticated web app with shadcn/ui components
          npm run build
          
          # Verify build output
          ls -la dist/public/
          
      - name: Prepare Capacitor configuration
        script: |
          # Create Capacitor config pointing to correct build directory
          cat > capacitor.config.ts << 'EOF'
          import { CapacitorConfig } from '@capacitor/cli';
          
          const config: CapacitorConfig = {
            appId: 'com.smartbudgettracker',
            appName: 'Smart Budget Tracker',
            webDir: 'dist/public',  // <- Fixed: points to correct directory
            server: {
              androidScheme: 'https'
            }
          };
          
          export default config;
          EOF
