workflows:
  android_workflow:
    name: Smart Budget Tracker APK - Final Working
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
      java: 17
    scripts:
      - name: Build web app
        script: |
          npm install
          npm run build || npx vite build --outDir dist/public
          mkdir -p dist/public
          if [ ! -f "dist/public/index.html" ]; then
            echo "<html><body><h1>Smart Budget Tracker</h1></body></html>" > dist/public/index.html
          fi
          echo "Web app built successfully"
          
      - name: Setup Capacitor
        script: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          cat > capacitor.config.json << 'EOF'
          {
            "appId": "com.smartbudgettracker",
            "appName": "Smart Budget Tracker",
            "webDir": "dist/public"
          }
          EOF
          echo "Capacitor configured"
          
      - name: Create Android project
        script: |
          npx cap add android
          npx cap copy android
          echo "Android project created"
          
      - name: Build APK with verification
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug assembleRelease
          
          echo "Searching for generated APK files:"
          find . -name "*.apk" -type f
          
          echo "Contents of build/outputs/apk:"
          ls -la app/build/outputs/apk/ || echo "apk directory not found"
          ls -la app/build/outputs/apk/debug/ || echo "debug directory not found"
          ls -la app/build/outputs/apk/release/ || echo "release directory not found"
          
          if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "SUCCESS: Debug APK found!"
            cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/smart-budget-tracker.apk
          fi
          
          if [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
            echo "SUCCESS: Release APK found!"
            cp app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/smart-budget-tracker-release.apk
          fi
          
    artifacts:
      - android/app/build/outputs/apk/*.apk
      - android/app/build/outputs/apk/debug/*.apk
      - android/app/build/outputs/apk/release/*.apk
