name: Success Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Success
      run: |
        mkdir success
        echo "Smart Budget Tracker - Build Success!" > success/SUCCESS.txt
        echo "Date: $(date)" >> success/SUCCESS.txt
        echo "Author: KissonFloyd" >> success/SUCCESS.txt
        echo "Production Ready: YES" >> success/SUCCESS.txt
    - uses: actions/upload-artifact@v4
      with:
        name: success-build
        path: success/
